name: "twilio-verify"
version: "3.8"

services:
  mongo:
    container_name: twilio-verify-mongo
    image: mongo:6.0
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./db/mongo/data:/data/db/
      - ./db/mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DBNAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PSSWD}

  mongo-express:
    image: mongo-express:latest
    container_name: twilio-verify-mongo-express
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PSSWD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PSSWD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PSSWD}@mongo:${MONGO_PORT}
